baseURL = 'https://ollybourne.com/'
locale = 'en-gb'
title = 'Olly Bourne'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  env = "staging"
  mainSections = []

  [params.profileMode]
  enabled = false
  title = "Hi, I'm Olly"
  subtitle = "## I'm a writer and strategist."
  imageUrl = "/images/headshot.jpeg"
  imageAlt = "Olly Bourne headshot"
  imageWidth = 120
  imageHeight = 120

[minify]
  disableXML = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 10

  [[menu.main]]
  name = "Fiction"
  url = "/fiction/"
  weight = 20

  [[menu.main]]
  name = "Resume"
  url = "/resume/"
  weight = 30