baseURL = 'https://olly-bourne.github.io/neptune-estate/'
locale = 'en-gb'
title = 'Olly Bourne'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

[minify]
  disableXML = true

[[menu.main]]
  name = "Why Work With Me?"
  url = "/why-work-with-me/"
  weight = 20